baseURL = 'https://shopping.nav8.top/'
languageCode = 'en-US'
title = "EasyBuy Global-Making Global Shopping Simple"

[pagination]       # <--- 添加这个配置块
  pagerSize = 10   # <--- 使用 pagerSize 并设置相同的值

[outputs]
  home = ["HTML", "RSS", "JSON"] # 为首页添加 JSON 输出
  # section = ["HTML", "RSS"] # 你也可以为 section 添加


[menus]

  [[menus.main]]
       identifier = "home"
       name = "Home"
       url = "/"
       weight = 10
  [[menus.main]]
       identifier = "north-america"
       name = "North-america"
       weight = 20
  [[menus.main]]
       parent = "north-america"
       identifier = "USA"
       name = "USA"
       url = "/shopping/us/"
       weight = 1
  [[menus.main]]
       parent = "north-america"
       identifier = "Canada"
       name = "Canada"
       url = "/shopping/ca/"
       weight = 2
  [[menus.main]]
       parent = "north-america"
       identifier = "Mexico"
       name = "Mexico"
       url = "/shopping/mx/"
       weight = 3
  [[menus.main]]
       identifier = "europe"
       name = "Europe"
       weight = 30
  [[menus.main]]
       parent = "europe"
       identifier = "UK"
       name = "UK"
       url = "/shopping/uk/"
       weight = 1
  [[menus.main]]
       parent = "europe"
       identifier = "France"
       name = "France"
       url = "/shopping/fr/"
       weight = 2
  [[menus.main]]
       parent = "europe"
       identifier = "Germany"
       name = "Germany"
       url = "/shopping/de/"
       weight = 3
  [[menus.main]]
       parent = "europe"
       identifier = "Switzerland"
       name = "Switzerland"
       url = "/shopping/ch/"
       weight = 4
  [[menus.main]]
       parent = "europe"
       identifier = "Sweden"
       name = "Sweden"
       url = "/shopping/se/"
       weight = 5
  [[menus.main]]
       parent = "europe"
       identifier = "Netherlands"
       name = "Netherlands"
       url = "/shopping/nl/"
       weight = 6
  [[menus.main]]
       parent = "europe"
       identifier = "Denmark"
       name = "Denmark"
       url = "/shopping/dk/"
       weight = 7
  [[menus.main]]
       parent = "europe"
       identifier = "Norway"
       name = "Norway"
       url = "/shopping/no/"
       weight = 8
  [[menus.main]]
       parent = "europe"
       identifier = "Finland"
       name = "Finland"
       url = "/shopping/fi/"
       weight = 9
  [[menus.main]]
       parent = "europe"
       identifier = "Poland"
       name = "Poland"
       url = "/shopping/pl/"
       weight = 10
  [[menus.main]]
       parent = "europe"
       identifier = "Greece"
       name = "Greece"
       url = "/shopping/gr/"
       weight = 11
  [[menus.main]]
       parent = "europe"
       identifier = "Czech"
       name = "Czech"
       url = "/shopping/cz/"
       weight = 12
  [[menus.main]]
       parent = "europe"
       identifier = "Italy"
       name = "Italy"
       url = "/shopping/it/"
       weight = 13
  [[menus.main]]
       parent = "europe"
       identifier = "Spain"
       name = "Spain"
       url = "/shopping/es/"
       weight = 14
  [[menus.main]]
       parent = "europe"
       identifier = "Ireland"
       name = "Ireland"
       url = "/shopping/ie/"
       weight = 15
  [[menus.main]]
       parent = "europe"
       identifier = "Belgium"
       name = "Belgium"
       url = "/shopping/be/"
       weight = 16
  [[menus.main]]
       identifier = "asia"
       name = "Asia"
       weight = 40
  [[menus.main]]
       parent = "asia"
       identifier = "China"
       name = "China"
       url = "/shopping/cn/"
       weight = 1
  [[menus.main]]
       parent = "asia"
       identifier = "Hong-Kong"
       name = "Hong-Kong"
       url = "/shopping/hk/"
       weight = 2
  [[menus.main]]
       parent = "asia"
       identifier = "Taiwan"
       name = "Taiwan"
       url = "/shopping/tw/"
       weight = 3
  [[menus.main]]
       parent = "asia"
       identifier = "Japan"
       name = "Japan"
       url = "/shopping/jp/"
       weight = 4
  [[menus.main]]
       parent = "asia"
       identifier = "Korea"
       name = "Korea"
       url = "/shopping/kr/"
       weight = 5
  [[menus.main]]
       parent = "asia"
       identifier = "Thailand"
       name = "Thailand"
       url = "/shopping/th/"
       weight = 6    
  [[menus.main]]
       parent = "asia"
       identifier = "India"
       name = "India"
       url = "/shopping/in/"
       weight = 7
  [[menus.main]]
       parent = "asia"
       identifier = "Indonesia"
       name = "Indonesia"
       url = "/shopping/id/"
       weight = 8
  [[menus.main]]
       parent = "asia"
       identifier = "Myanmar"
       name = "Myanmar"
       url = "/shopping/mm/"
       weight = 9
  [[menus.main]]
       parent = "asia"
       identifier = "Vietnam"
       name = "Vietnam"
       url = "/shopping/vn/"
       weight = 10
  [[menus.main]]
       parent = "asia"
       identifier = "Singapore"
       name = "Singapore"
       url = "/shopping/sg/"
       weight = 11
  [[menus.main]]
       parent = "asia"
       identifier = "Philippines"
       name = "Philippines"
       url = "/shopping/ph/"
       weight = 12    
  [[menus.main]]
       parent = "asia"
       identifier = "Malaysia"
       name = "Malaysia"
       url = "/shopping/my/"
       weight = 13
  [[menus.main]]
       parent = "asia"
       identifier = "United-Arab-Emirates"
       name = "United-Arab-Emirates"
       url = "/shopping/ae/"
       weight = 14
  [[menus.main]]
       parent = "asia"
       identifier = "Turkey"
       name = "Turkey"
       url = "/shopping/tr/"
       weight = 15
  [[menus.main]]
       parent = "asia"
       identifier = "Qatar"
       name = "Qatar"
       url = "/shopping/qa/"
       weight = 16
  [[menus.main]]
       identifier = "oceania"
       name = "Oceania"
       weight = 50
  [[menus.main]]
       parent = "oceania"
       identifier = "Australia"
       name = "Australia"
       url = "/shopping/au/"
       weight = 2
  [[menus.main]]
       parent = "oceania"
       identifier = "New-Zealand"
       name = "New-Zealand"
       url = "/shopping/nz/"
       weight = 3
  [[menus.main]]
       identifier = "south-america"
       name = "South-america"
       weight = 60
  [[menus.main]]
       parent = "south-america"
       identifier = "Brazil"
       name = "Brazil"
       url = "/shopping/br/"
       weight = 1
  [[menus.main]]
       parent = "south-america"
       identifier = "Chile"
       name = "Chile"
       url = "/shopping/cl/"
       weight = 2
  [[menus.main]]
       parent = "south-america"
       identifier = "Argentina"
       name = "Argentina"
       url = "/shopping/ar/"
       weight = 3
  [[menus.main]]
       parent = "south-america"
       identifier = "Colombia"
       name = "Colombia"
       url = "/shopping/co/"
       weight = 4
  [[menus.main]]
       parent = "south-america"
       identifier = "Peru"
       name = "Peru"
       url = "/shopping/pe/"
       weight = 5
  [[menus.main]]
       identifier = "africa"
       name = "Africa"
       weight = 70
  [[menus.main]]
       parent = "africa"
       identifier = "South-Africa"
       name = "South-Africa"
       url = "/shopping/za/"
       weight = 1
  [[menus.main]]
       parent = "africa"
       identifier = "Egypt"
       name = "Egypt"
       url = "/shopping/eg/"
       weight = 2
  [[menus.main]]
       parent = "africa"
       identifier = "Ghana"
       name = "Ghana"
       url = "/shopping/gh/"
       weight = 3
  [[menus.main]]
       parent = "africa"
       identifier = "Morocco"
       name = "Morocco"
       url = "/shopping/ma/"
       weight = 4
  [[menus.main]]
       parent = "africa"
       identifier = "Kenya"
       name = "Kenya"
       url = "/shopping/ke/"
       weight = 5
  [[menus.main]]
       parent = "africa"
       identifier = "Nigeria"
       name = "Nigeria"
       url = "/shopping/ng/"
       weight = 6
  [[menus.main]]
       parent = "africa"
       identifier = "Côte-d'Ivoire"
       name = "Côte-d'Ivoire"
       url = "/shopping/ci/"
       weight = 7    


[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[params]
  # ...
  mainSections = ["shopping", "docs"] # 只索引 posts 和 docs section 的内容
  description = "EasyBuy Global is your expert guide to worldwide shopping, gathering thousands of well-known shopping platforms from around the globe. Covering a wide range of categories including fashion, beauty, maternity and baby products, and more, we provide real-time updates, intelligent recommendations, and multilingual support to help you easily explore quality products worldwide and enjoy a premium lifestyle."
  keywords = ["EasyBuy Global","Global Shopping Navigation","Cross-border Shopping Platform Recommendations","Global Quality Products","EasyBuy Global Navigation","Global Shopping Guide","Cross-border Shopping Tips","International Shopping Platforms","Global Product Recommendations","Cross-border Shopping Assistant"]
  favicon = "images/icons/favicon.ico"
  dateFormat = "January 2nd, 2006"
  enablePWA = true

  # --- 页脚配置 ---
  [params.footer]
    # 控制是否显示页脚菜单
    showFooterMenu = true # 确保这个是 true

    # 定义页脚菜单项 - 这是我们要测试的部分
    [[params.footer.menu]]
      name = "Home"
      url = "/"

    [[params.footer.menu]]
      name = "About Us"
      url = "/about/"

    [[params.footer.menu]]
      name = "Contact Us"
      url = "/about/#联系我们"

    [[params.footer.menu]]
      name = "USA Shopping"
      url = "/shopping/usa/"

    [[params.footer.menu]]
      name = "Canada Shopping"
      url = "/shopping/ca/"

    [[params.footer.menu]]
      name = "UK Shopping"
      url = "/shopping/uk/"

    [[params.footer.menu]]
      name = "France Shopping"
      url = "/shopping/fr/"

    [[params.footer.menu]]
      name = "Italy Shopping"
      url = "/shopping/it/"

    [[params.footer.menu]]
      name = "Japan Shopping"
      url = "/shopping/jp/"

    [[params.footer.menu]]
      name = "Korea Shopping"
      url = "/shopping/kr/"

    [[params.footer.menu]]
      name = "Australia Shopping"
      url = "/shopping/au/"

    # 版本 Widget (这是我们要配置的部分)
    [params.footer.widgets.editions]
      enable = true        # 是否启用这个 Widget
      title = "Luxury brand"  # Widget 的标题
      items = [            # 链接列表
        { name = "Giorgio Armani", url = "https://sovrn.co/2kxgm4u" }, # name 显示文本, url 链接目标
        { name = "Balenciaga", url = "#" },
        { name = "Hermès", url = "#" },
        { name = "Chanel", url = "#" },
        { name = "Gucci", url = "https://sovrn.co/m558eh9" },
        { name = "Prada", url = "https://sovrn.co/1ngq4pw" }, # 外部链接
        { name = "Fendi", url = "#" },
        { name = "Versace", url = "#" },
        { name = "Christian Dior", url = "#" }, # 外部链接
        { name = "Louis Vuitton", url = "#" }, # 外部链接
        { name = "Rolex", url = "#" }, # name 是显示文本, url 是链接目标
      ]      
  
    # 版本 Widget (这是我们要配置的部分)
    [params.footer.widgets.tags]
      enable = true        # 是否启用这个 Widget


      # 产品 Widget (这是我们要配置的部分)
    [params.footer.widgets.products]
      enable = true            # 是否启用这个 Widget
      title = "Famous shopping website"       # Widget 的标题
      items = [                # 链接列表
        { name = "Alibaba", url = "https://sovrn.co/1b4yyqm" }, # name 是显示文本, url 是链接目标
        { name = "Amazon", url = "https://sovrn.co/nutetc6" },
        { name = "eBay", url = "https://sovrn.co/s6ks5mb" }, # 可以是站内相对路径
        { name = "Shein", url = "https://sovrn.co/ljsf81h" }, # 也可以是页面内锚点
        { name = "JD", url = "https://sovrn.co/0292ku7" },
        { name = "Shopify", url = "https://sovrn.co/1am1n7g" },
        { name = "AliExpress", url = "https://sovrn.co/2f7rrq3" }, # 外部链接
        { name = "Temu", url = "https://sovrn.co/1bwduhq" },
        { name = "TARGET", url = "https://sovrn.co/z8kvqi4" },
        { name = "Macys", url = "https://sovrn.co/zqo5fwg" },
      ]

  # 首页顶部广告
  [params.headerMiddleAd]
  enable = true # 只在特定页面或全局启用,logo右侧广告位
  imageUrl = "images/others/top-ad.jpg" # 相对于 static
  linkUrl = "https://example-advertiser.com/header-ad"
  altText = "logo右侧广告位"
  
  [params.homepageTopAd]
    enable = false
    imageUrl = "images/others/ad1.jpg" # 相对于 static 目录
    linkUrl = "https://www.example-advertiser.com/homepage-offer"
    altText = "首页顶部广告"

  # 首页底部广告
  [params.homepageFootAd]
    enable = false
    imageUrl = "images/others/ad1.jpg" # 相对于 static 目录
    linkUrl = "https://www.example-advertiser.com/homepage-offer"
    altText = "首页底部广告"

  # 侧边栏广告位 1 (原始HTML中的 ad4.jpg)
  [params.sidebarAd1]
    enable = false
    imageUrl = "images/others/ad4.jpg" # 相对于 static 目录
    linkUrl = "https://www.example-advertiser.com/sidebar-offer-1"
    altText = "侧边栏广告一"

  # 侧边栏广告位 2 (原始HTML中的 ad5.jpg)
  [params.sidebarAd2]
    enable = false
    imageUrl = "images/others/ad5.jpg" # 相对于 static 目录
    linkUrl = "https://www.example-advertiser.com/sidebar-offer-2"
    altText = "侧边栏广告二"

  # 你可以根据需要添加更多广告位
  # [params.anotherAd]
  #   enable = false # 可以用 enable 来控制是否显示
  #   imageUrl = "images/ads/another.png"
  #   linkUrl = "#"
  #   altText = "另一个广告"


  [params.homeSliderAd] # 首页主轮播图右侧的广告 (原 add1.jpg)
  enable = true
  imageUrl = "images/others/add1.jpg"
  linkUrl = "#"
  altText = "特色广告"

[params.homepageMiddleAdV2] # 首页主轮播图下方的广告 (原 ad1.jpg)
  enable = true
  imageUrl = "images/others/ad1.jpg"
  linkUrl = "#"
  altText = "横幅广告"

[params.homepageContentAd1] # 内容区第一个广告
  enable = true
  imageUrl = "images/others/ad1.jpg" # 示例，替换为你的广告图片
  linkUrl = "#"
  altText = "内容广告1"

[params.homepageContentAd2] # 内容区第二个广告
  enable = true
  imageUrl = "images/others/ad1.jpg" # 示例，替换为你的广告图片
  linkUrl = "#"
  altText = "内容广告2"

  [params.social]
  facebook = "https://facebook.com/yourpage"
  twitter = "https://twitter.com/yourhandle"
  # ...




[related]
  threshold = 80 # 匹配度阈值
  includeNewer = true
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 80
  [[related.indices]]
    name = "date"
    weight = 10
    pattern = "2006" # 例如，按年份匹配  


[markup.goldmark.renderer]
  unsafe = true # Needed if you use raw HTML like <span class="dropcap"> in Markdown
